export const LOG_EVENT = 'LOG_EVENT';
export const LOG_EVENT_SUCCESS = 'LOG_EVENT_SUCCESS';
export const LOG_EVENT_FAILURE = 'LOG_EVENT_FAILURE';

export const LOG_EXCEPTION = 'LOG_EXCEPTION';
export const LOG_EXCEPTION_SUCCESS = 'LOG_EXCEPTION_SUCCESS';
export const LOG_EXCEPTION_FAILURE = 'LOG_EXCEPTION_FAILURE';

export const TRACK_PAGE_VIEW = 'TRACK_PAGE_VIEW';
export const TRACK_PAGE_VIEW_SUCCESS = 'TRACK_PAGE_VIEW_SUCCESS';
export const TRACK_PAGE_VIEW_FAIL = 'TRACK_PAGE_VIEW_FAIL';

export const INIT_LOGGING = 'INIT_LOGGING';
