export const GET_MACHINES_REQUEST = 'GET_MACHINES_REQUEST';
export const GET_MACHINES_SUCCESS = 'GET_MACHINES_SUCCESS';
export const GET_MACHINES_FAILURE = 'GET_MACHINES_FAILURE';

export const ADD_MACHINE_REQUEST = 'ADD_MACHINE_REQUEST';
export const ADD_MACHINE_SUCCESS = 'ADD_MACHINE_SUCCESS';
export const ADD_MACHINE_FAILURE = 'ADD_MACHINE_FAILURE';

export const EDIT_MACHINE_REQUEST = 'EDIT_MACHINE_REQUEST';
export const EDIT_MACHINE_SUCCESS = 'EDIT_MACHINE_SUCCESS';
export const EDIT_MACHINE_FAILURE = 'EDIT_MACHINE_FAILURE';

export const SELECT_MACHINE = 'SELECT_MACHINE';
